IDIR	=../include
CC      = g++
CFLAGS  = -I.$(IDIR)

ODIR	= ./obj
LDIR	=../lib

LIBS	=-lm

_DEPS	= arvore.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = testa_arvore.o arvore.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

$(ODIR)/%.o: %.c $(DEPS)
		$(CC)	-c	-o 	$@	$<	$(CFLAGS)

$(ODIR)/%.o: %.cpp $(DEPS)
		$(CC)	-c	-o 	$@	$<	$(CFLAGS)

testa_arvore: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~
